// <auto-generated />
using System;
using IPNoticeHub.Data;
using IPNoticeHub.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace IPNoticeHub.Data.Migrations
{
    [DbContext(typeof(IPNoticeHubDbContext))]
    [Migration("20250825185747_SeedFakeData")]
    partial class SeedFakeData
    {
        /// <inheritdoc />
        protected void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.19")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("IPNoticeHub.Data.Entities.Identity", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.ToTable("AspNetUsers", (string)null);

                    b.HasData(
                        new
                        {
                            Id = "2b195b12-9690-46b9-ac8e-50118a7102ea",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "73dd29f5-cb9c-4f43-84ae-73597cded863",
                            Email = "testuser1@example.com",
                            EmailConfirmed = true,
                            LockoutEnabled = false,
                            NormalizedEmail = "TESTUSER1@EXAMPLE.COM",
                            NormalizedUserName = "TESTUSER1@EXAMPLE.COM",
                            PasswordHash = "AQAAAAIAAYagAAAAEFakeHash1234567890==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "6fc62e55-dbc8-4022-84b4-cd49bdb663a3",
                            TwoFactorEnabled = false,
                            UserName = "testuser1@example.com"
                        },
                        new
                        {
                            Id = "4d8f7a3e-cb13-42f4-bf61-0a8c301a3f8b",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "d1d41029-3bbf-4476-890a-d64104220466",
                            Email = "testuser2@example.com",
                            EmailConfirmed = true,
                            LockoutEnabled = false,
                            NormalizedEmail = "TESTUSER2@EXAMPLE.COM",
                            NormalizedUserName = "TESTUSER2@EXAMPLE.COM",
                            PasswordHash = "AQAAAAIAAYagFakeHash0987654321==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "abc60a70-c408-4762-be78-c7c0d1ea3b9b",
                            TwoFactorEnabled = false,
                            UserName = "testuser2@example.com"
                        });
                });

            modelBuilder.Entity("IPNoticeHub.Data.Entities.CopyrightRegistration", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasComment("Primary key for the Copyright entity");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("DateOfPublication")
                        .HasColumnType("datetime2")
                        .HasComment("Date of publication, if the work has been published");

                    b.Property<string>("NationOfFirstPublication")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasComment("Nation of first publication");

                    b.Property<string>("Owner")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasComment("Copyright claimant, usually the author or company");

                    b.Property<Guid>("PublicId")
                        .HasColumnType("uniqueidentifier")
                        .HasComment("Public identifier for the copyright (e.g. Registration Number)");

                    b.Property<string>("RegistrationNumber")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasComment("Official copyright registration number, e.g. VA0002288838");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)")
                        .HasComment("Title of the work being registered");

                    b.Property<string>("TypeOfWork")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasComment("Type of work, e.g. Literary Work, Visual Material, Music, Software");

                    b.Property<int?>("YearOfCreation")
                        .HasColumnType("int")
                        .HasComment("Year of creation of the work (if provided)");

                    b.HasKey("Id");

                    b.HasIndex("RegistrationNumber")
                        .IsUnique();

                    b.ToTable("CopyrightRegistrations");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            DateOfPublication = new DateTime(2020, 4, 16, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            NationOfFirstPublication = "United States",
                            Owner = "Nikolay Todorov",
                            PublicId = new Guid("076d6d16-235d-40e7-b419-da5465d8ebdf"),
                            RegistrationNumber = "VA0002288838",
                            Title = "Astronaut Music DJ",
                            TypeOfWork = "Visual Material",
                            YearOfCreation = 2020
                        });
                });

            modelBuilder.Entity("IPNoticeHub.Data.Entities.TrademarkClassAssignment", b =>
                {
                    b.Property<int>("TrademarkRegistrationId")
                        .HasColumnType("int");

                    b.Property<int>("ClassNumber")
                        .HasColumnType("int")
                        .HasComment("The Nice Classification number (1–45) assigned to this trademark.");

                    b.HasKey("TrademarkRegistrationId", "ClassNumber");

                    b.ToTable("TrademarkClassAssignment");

                    b.HasData(
                        new
                        {
                            TrademarkRegistrationId = 1,
                            ClassNumber = 25
                        },
                        new
                        {
                            TrademarkRegistrationId = 2,
                            ClassNumber = 25
                        },
                        new
                        {
                            TrademarkRegistrationId = 2,
                            ClassNumber = 28
                        });
                });

            modelBuilder.Entity("IPNoticeHub.Data.Entities.TrademarkEvent", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasComment("Primary key for the TrademarkEvent entity");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)")
                        .HasComment("Code representing the event type or category");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)")
                        .HasComment("Detailed description of the event");

                    b.Property<DateTime>("EventDate")
                        .HasColumnType("datetime2")
                        .HasComment("The date when the event occurred");

                    b.Property<int>("EventType")
                        .HasColumnType("int")
                        .HasComment("Enum representing the type of the event");

                    b.Property<string>("EventTypeRaw")
                        .HasMaxLength(2)
                        .HasColumnType("nvarchar(2)")
                        .HasComment("Raw event type code as received from the source system");

                    b.Property<int>("TrademarkId")
                        .HasColumnType("int")
                        .HasComment("Foreign key referencing the associated TrademarkRegistration");

                    b.HasKey("Id");

                    b.HasIndex("TrademarkId");

                    b.ToTable("TrademarkEvents");
                });

            modelBuilder.Entity("IPNoticeHub.Data.Entities.TrademarkRegistration", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasComment("Primary key for the Trademark entity");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("FilingDate")
                        .HasColumnType("datetime2")
                        .HasComment("Filing date of the trademark application (optional)");

                    b.Property<string>("GoodsAndServices")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)")
                        .HasComment("Description of goods and services associated with the trademark");

                    b.Property<string>("MarkImageUrl")
                        .HasMaxLength(2048)
                        .HasColumnType("nvarchar(2048)")
                        .HasComment("URL of the image representing the trademark (optional)");

                    b.Property<string>("Owner")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasComment("Name of the current owner/s of the trademark");

                    b.Property<Guid>("PublicId")
                        .HasColumnType("uniqueidentifier")
                        .HasComment("Unique identifier for the Trademark, generated automatically");

                    b.Property<DateTime?>("RegistrationDate")
                        .HasColumnType("datetime2")
                        .HasComment("Registration date of the trademark (optional)");

                    b.Property<string>("RegistrationNumber")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasComment("Registration number of the trademark (optional)");

                    b.Property<int>("Source")
                        .HasColumnType("int")
                        .HasComment("Source of the data for the trademark registration");

                    b.Property<string>("SourceId")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasComment("Original identifier from the source system (USPTO Serial, EUIPO Application, WIPO IRN)");

                    b.Property<int>("StatusCategory")
                        .HasColumnType("int")
                        .HasComment("Current status of the trademark (default is Pending)");

                    b.Property<string>("StatusDetail")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("Wordmark")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)")
                        .HasComment("The wordmark or name of the trademark)");

                    b.HasKey("Id");

                    b.HasIndex("Source", "SourceId")
                        .IsUnique();

                    b.ToTable("TrademarkRegistrations");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            FilingDate = new DateTime(2010, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            GoodsAndServices = "Clothing, footwear, headgear",
                            Owner = "Nike Inc.",
                            PublicId = new Guid("4dd1f011-5362-42ff-9853-33ccbe4aa935"),
                            RegistrationDate = new DateTime(2012, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            RegistrationNumber = "54321",
                            Source = 0,
                            SourceId = "123456",
                            StatusCategory = 1,
                            StatusDetail = "Live/Registered",
                            Wordmark = "Nike"
                        },
                        new
                        {
                            Id = 2,
                            FilingDate = new DateTime(2015, 5, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            GoodsAndServices = "Sports equipment, clothing",
                            Owner = "Adidas AG",
                            PublicId = new Guid("fdb6b78f-6f5c-42ec-8b36-9a958011168b"),
                            RegistrationDate = new DateTime(2017, 6, 6, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            RegistrationNumber = "98765",
                            Source = 0,
                            SourceId = "654321",
                            StatusCategory = 1,
                            StatusDetail = "Live/Registered",
                            Wordmark = "Adidas"
                        });
                });

            modelBuilder.Entity("IPNoticeHub.Data.Entities.UserCopyright", b =>
                {
                    b.Property<string>("ApplicationUserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("CopyrightRegistrationId")
                        .HasColumnType("int");

                    b.Property<DateTime>("DateAdded")
                        .HasColumnType("datetime2")
                        .HasComment("Date when the user added this copyright registration to their account");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit")
                        .HasComment("Indicates whether the user soft-deleted this from their collection/watchlist");

                    b.HasKey("ApplicationUserId", "CopyrightRegistrationId");

                    b.HasIndex("CopyrightRegistrationId");

                    b.ToTable("UserCopyright");

                    b.HasData(
                        new
                        {
                            ApplicationUserId = "2b195b12-9690-46b9-ac8e-50118a7102ea",
                            CopyrightRegistrationId = 1,
                            DateAdded = new DateTime(2025, 8, 25, 18, 57, 46, 431, DateTimeKind.Utc).AddTicks(7182),
                            IsDeleted = false
                        });
                });

            modelBuilder.Entity("IPNoticeHub.Data.Entities.UserTrademark", b =>
                {
                    b.Property<string>("ApplicationUserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("TrademarkRegistrationId")
                        .HasColumnType("int");

                    b.Property<bool>("AddedToWatchlist")
                        .HasColumnType("bit")
                        .HasComment("Indicates whether the trademark is on a watchlist");

                    b.Property<DateTime>("DateAdded")
                        .HasColumnType("datetime2")
                        .HasComment("Date when the user added this trademark registration to their account");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit")
                        .HasComment("Indicates whether the user has removed this registration from their collection or watchlist (soft delete).");

                    b.HasKey("ApplicationUserId", "TrademarkRegistrationId");

                    b.HasIndex("TrademarkRegistrationId");

                    b.ToTable("UserTrademark");

                    b.HasData(
                        new
                        {
                            ApplicationUserId = "2b195b12-9690-46b9-ac8e-50118a7102ea",
                            TrademarkRegistrationId = 1,
                            AddedToWatchlist = true,
                            DateAdded = new DateTime(2025, 8, 25, 18, 57, 46, 431, DateTimeKind.Utc).AddTicks(7161),
                            IsDeleted = false
                        },
                        new
                        {
                            ApplicationUserId = "4d8f7a3e-cb13-42f4-bf61-0a8c301a3f8b",
                            TrademarkRegistrationId = 2,
                            AddedToWatchlist = false,
                            DateAdded = new DateTime(2025, 8, 25, 18, 57, 46, 431, DateTimeKind.Utc).AddTicks(7164),
                            IsDeleted = false
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("AspNetRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("ProviderKey")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("RoleId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("LoginProvider")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("Name")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("IPNoticeHub.Data.Entities.TrademarkClassAssignment", b =>
                {
                    b.HasOne("IPNoticeHub.Data.Entities.TrademarkRegistration", "TrademarkRegistration")
                        .WithMany("Classes")
                        .HasForeignKey("TrademarkRegistrationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("TrademarkRegistration");
                });

            modelBuilder.Entity("IPNoticeHub.Data.Entities.TrademarkEvent", b =>
                {
                    b.HasOne("IPNoticeHub.Data.Entities.TrademarkRegistration", "TrademarkRegistration")
                        .WithMany("Events")
                        .HasForeignKey("TrademarkId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("TrademarkRegistration");
                });

            modelBuilder.Entity("IPNoticeHub.Data.Entities.UserCopyright", b =>
                {
                    b.HasOne("IPNoticeHub.Data.Entities.Identity", "ApplicationUser")
                        .WithMany("UserCopyrights")
                        .HasForeignKey("ApplicationUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("IPNoticeHub.Data.Entities.CopyrightRegistration", "CopyrightRegistration")
                        .WithMany("UserCopyrights")
                        .HasForeignKey("CopyrightRegistrationId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("ApplicationUser");

                    b.Navigation("CopyrightRegistration");
                });

            modelBuilder.Entity("IPNoticeHub.Data.Entities.UserTrademark", b =>
                {
                    b.HasOne("IPNoticeHub.Data.Entities.Identity", "ApplicationUser")
                        .WithMany("UserTrademarks")
                        .HasForeignKey("ApplicationUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("IPNoticeHub.Data.Entities.TrademarkRegistration", "TrademarkRegistration")
                        .WithMany("UserTrademarks")
                        .HasForeignKey("TrademarkRegistrationId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("ApplicationUser");

                    b.Navigation("TrademarkRegistration");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("IPNoticeHub.Data.Entities.Identity", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("IPNoticeHub.Data.Entities.Identity", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("IPNoticeHub.Data.Entities.Identity", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("IPNoticeHub.Data.Entities.Identity", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("IPNoticeHub.Data.Entities.Identity", b =>
                {
                    b.Navigation("UserCopyrights");

                    b.Navigation("UserTrademarks");
                });

            modelBuilder.Entity("IPNoticeHub.Data.Entities.CopyrightRegistration", b =>
                {
                    b.Navigation("UserCopyrights");
                });

            modelBuilder.Entity("IPNoticeHub.Data.Entities.TrademarkRegistration", b =>
                {
                    b.Navigation("Classes");

                    b.Navigation("Events");

                    b.Navigation("UserTrademarks");
                });
#pragma warning restore 612, 618
        }
    }
}
