// <auto-generated />
using System;
using IPNoticeHub.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace IPNoticeHub.Infrastructure.Migrations
{
    [DbContext(typeof(IPNoticeHubDbContext))]
    partial class IPNoticeHubDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.19")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("IPNoticeHub.Domain.Entities.Copyrights.CopyrightEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("DateOfPublication")
                        .HasColumnType("datetime2");

                    b.Property<string>("NationOfFirstPublication")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Owner")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<Guid>("PublicId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("RegistrationNumber")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.Property<string>("TypeOfWork")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int?>("YearOfCreation")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("RegistrationNumber")
                        .IsUnique();

                    b.ToTable("CopyrightRegistrations");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            DateOfPublication = new DateTime(2020, 4, 16, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            NationOfFirstPublication = "United States",
                            Owner = "Nikolay Todorov",
                            PublicId = new Guid("076d6d16-235d-40e7-b419-da5465d8ebdf"),
                            RegistrationNumber = "VA0002288838",
                            Title = "Astronaut Music DJ",
                            TypeOfWork = "Visual Material",
                            YearOfCreation = 2020
                        },
                        new
                        {
                            Id = 2,
                            DateOfPublication = new DateTime(2024, 6, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            NationOfFirstPublication = "United States",
                            Owner = "IPNoticeHub Ltd.",
                            PublicId = new Guid("c1d0c5bf-0b4b-4c9a-9cc0-2a3c9b2b0f11"),
                            RegistrationNumber = "TX0009990001",
                            Title = "IPNoticeHub – Terms & Templates Collection",
                            TypeOfWork = "Literary Work",
                            YearOfCreation = 2024
                        },
                        new
                        {
                            Id = 3,
                            DateOfPublication = new DateTime(2024, 9, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            NationOfFirstPublication = "United States",
                            Owner = "IPNoticeHub Ltd.",
                            PublicId = new Guid("b7a97c4a-6ee3-4b2f-a7b2-5b3a1d1a7c77"),
                            RegistrationNumber = "TX0009990002",
                            Title = "IPNoticeHub – Core Services",
                            TypeOfWork = "Computer Program",
                            YearOfCreation = 2024
                        });
                });

            modelBuilder.Entity("IPNoticeHub.Domain.Entities.Identity.UserCopyright", b =>
                {
                    b.Property<string>("ApplicationUserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("CopyrightEntityId")
                        .HasColumnType("int");

                    b.Property<DateTime>("DateAdded")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.HasKey("ApplicationUserId", "CopyrightEntityId");

                    b.HasIndex("CopyrightEntityId");

                    b.HasIndex("ApplicationUserId", "CopyrightEntityId")
                        .IsUnique();

                    b.ToTable("UserCopyrights");

                    b.HasData(
                        new
                        {
                            ApplicationUserId = "2b195b12-9690-46b9-ac8e-50118a7102ea",
                            CopyrightEntityId = 1,
                            DateAdded = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsDeleted = false
                        },
                        new
                        {
                            ApplicationUserId = "2b195b12-9690-46b9-ac8e-50118a7102ea",
                            CopyrightEntityId = 2,
                            DateAdded = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsDeleted = false
                        },
                        new
                        {
                            ApplicationUserId = "4d8f7a3e-cb13-42f4-bf61-0a8c301a3f8b",
                            CopyrightEntityId = 3,
                            DateAdded = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsDeleted = false
                        });
                });

            modelBuilder.Entity("IPNoticeHub.Domain.Entities.Identity.UserTrademark", b =>
                {
                    b.Property<string>("ApplicationUserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("TrademarkEntityId")
                        .HasColumnType("int");

                    b.Property<DateTime>("DateAdded")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.HasKey("ApplicationUserId", "TrademarkEntityId");

                    b.HasIndex("TrademarkEntityId");

                    b.ToTable("UserTrademarks");

                    b.HasData(
                        new
                        {
                            ApplicationUserId = "2b195b12-9690-46b9-ac8e-50118a7102ea",
                            TrademarkEntityId = 1,
                            DateAdded = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsDeleted = false
                        },
                        new
                        {
                            ApplicationUserId = "4d8f7a3e-cb13-42f4-bf61-0a8c301a3f8b",
                            TrademarkEntityId = 2,
                            DateAdded = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsDeleted = false
                        },
                        new
                        {
                            ApplicationUserId = "2b195b12-9690-46b9-ac8e-50118a7102ea",
                            TrademarkEntityId = 3,
                            DateAdded = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsDeleted = false
                        },
                        new
                        {
                            ApplicationUserId = "4d8f7a3e-cb13-42f4-bf61-0a8c301a3f8b",
                            TrademarkEntityId = 4,
                            DateAdded = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsDeleted = false
                        });
                });

            modelBuilder.Entity("IPNoticeHub.Domain.Entities.LegalDocuments.LegalDocument", b =>
                {
                    b.Property<int>("LegalDocumentId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("LegalDocumentId"));

                    b.Property<string>("AdditionalFacts")
                        .HasMaxLength(2048)
                        .HasColumnType("nvarchar(2048)");

                    b.Property<string>("ApplicationUserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("BodyTemplate")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedOn")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DateOfPublication")
                        .HasColumnType("datetime2");

                    b.Property<string>("DocumentTitle")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("GoodFaithStatement")
                        .HasMaxLength(2048)
                        .HasColumnType("nvarchar(2048)");

                    b.Property<string>("InfringingUrl")
                        .HasMaxLength(2048)
                        .HasColumnType("nvarchar(2048)");

                    b.Property<string>("IpTitle")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<DateTime>("LetterDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("NationOfFirstPublication")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("RecipientAddress")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("nvarchar(512)");

                    b.Property<string>("RecipientEmail")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("RecipientName")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("RegistrationNumber")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<Guid>("RelatedPublicId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("SenderAddress")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("nvarchar(512)");

                    b.Property<string>("SenderEmail")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("SenderName")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<int>("SourceType")
                        .HasColumnType("int");

                    b.Property<int>("TemplateType")
                        .HasColumnType("int");

                    b.Property<int?>("YearOfCreation")
                        .HasColumnType("int");

                    b.HasKey("LegalDocumentId");

                    b.HasIndex("ApplicationUserId");

                    b.ToTable("LegalDocuments");
                });

            modelBuilder.Entity("IPNoticeHub.Domain.Entities.Trademarks.TrademarkClassAssignment", b =>
                {
                    b.Property<int>("TrademarkRegistrationId")
                        .HasColumnType("int");

                    b.Property<int>("ClassNumber")
                        .HasColumnType("int");

                    b.HasKey("TrademarkRegistrationId", "ClassNumber");

                    b.ToTable("TrademarkClassAssignment");

                    b.HasData(
                        new
                        {
                            TrademarkRegistrationId = 1,
                            ClassNumber = 25
                        },
                        new
                        {
                            TrademarkRegistrationId = 2,
                            ClassNumber = 25
                        },
                        new
                        {
                            TrademarkRegistrationId = 2,
                            ClassNumber = 28
                        },
                        new
                        {
                            TrademarkRegistrationId = 3,
                            ClassNumber = 9
                        },
                        new
                        {
                            TrademarkRegistrationId = 3,
                            ClassNumber = 42
                        },
                        new
                        {
                            TrademarkRegistrationId = 4,
                            ClassNumber = 35
                        },
                        new
                        {
                            TrademarkRegistrationId = 4,
                            ClassNumber = 42
                        });
                });

            modelBuilder.Entity("IPNoticeHub.Domain.Entities.Trademarks.TrademarkEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("FilingDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("GoodsAndServices")
                        .IsRequired()
                        .HasMaxLength(4000)
                        .HasColumnType("nvarchar(4000)");

                    b.Property<string>("MarkImageUrl")
                        .HasMaxLength(2048)
                        .HasColumnType("nvarchar(2048)");

                    b.Property<string>("Owner")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<Guid>("PublicId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("RegistrationDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("RegistrationNumber")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("Source")
                        .HasColumnType("int");

                    b.Property<string>("SourceId")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("StatusCategory")
                        .HasColumnType("int");

                    b.Property<int?>("StatusCodeRaw")
                        .HasColumnType("int");

                    b.Property<DateTime?>("StatusDateUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("StatusDetail")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<string>("Wordmark")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.HasKey("Id");

                    b.HasIndex("RegistrationNumber");

                    b.HasIndex("SourceId");

                    b.HasIndex("Source", "SourceId")
                        .IsUnique()
                        .HasDatabaseName("UX_Trademark_Source_SourceId");

                    b.ToTable("TrademarkRegistrations");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            FilingDate = new DateTime(2010, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            GoodsAndServices = "Clothing, footwear, headgear",
                            Owner = "Nike Inc.",
                            PublicId = new Guid("4dd1f011-5362-42ff-9853-33ccbe4aa935"),
                            RegistrationDate = new DateTime(2012, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            RegistrationNumber = "54321",
                            Source = 0,
                            SourceId = "123456",
                            StatusCategory = 1,
                            StatusDetail = "Live/Registered",
                            Wordmark = "Nike"
                        },
                        new
                        {
                            Id = 2,
                            FilingDate = new DateTime(2015, 5, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            GoodsAndServices = "Sports equipment, clothing",
                            Owner = "Adidas AG",
                            PublicId = new Guid("fdb6b78f-6f5c-42ec-8b36-9a958011168b"),
                            RegistrationDate = new DateTime(2017, 6, 6, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            RegistrationNumber = "98765",
                            Source = 0,
                            SourceId = "654321",
                            StatusCategory = 1,
                            StatusDetail = "Live/Registered",
                            Wordmark = "Adidas"
                        },
                        new
                        {
                            Id = 3,
                            FilingDate = new DateTime(2023, 2, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            GoodsAndServices = "Software as a service (SaaS) for IP monitoring and document generation",
                            Owner = "IPNoticeHub Ltd.",
                            PublicId = new Guid("7a6b6f2b-3e1d-4c44-9b4b-9aef4e4f3a10"),
                            RegistrationDate = new DateTime(2024, 1, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            RegistrationNumber = "11111",
                            Source = 0,
                            SourceId = "IPN-0001",
                            StatusCategory = 1,
                            StatusDetail = "Live/Registered",
                            Wordmark = "IPNOTICEHUB"
                        },
                        new
                        {
                            Id = 4,
                            FilingDate = new DateTime(2022, 10, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            GoodsAndServices = "Cloud security consulting and DevOps deployment services",
                            Owner = "Cloud Armor Group",
                            PublicId = new Guid("2bdb1d8a-1a11-4b3a-92f7-2c56e1c6f0c2"),
                            RegistrationDate = new DateTime(2023, 8, 20, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            RegistrationNumber = "22222",
                            Source = 0,
                            SourceId = "CA-2040",
                            StatusCategory = 1,
                            StatusDetail = "Live/Registered",
                            Wordmark = "CLOUDARMOR"
                        });
                });

            modelBuilder.Entity("IPNoticeHub.Domain.Entities.Trademarks.TrademarkEvent", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<DateTime>("EventDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("EventType")
                        .HasColumnType("int");

                    b.Property<string>("EventTypeRaw")
                        .HasMaxLength(2)
                        .HasColumnType("nvarchar(2)");

                    b.Property<int>("TrademarkId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("TrademarkId");

                    b.ToTable("TrademarkEvents");
                });

            modelBuilder.Entity("IPNoticeHub.Domain.Entities.Watchlist.Watchlist", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("AddedOnUtc")
                        .HasColumnType("datetime2");

                    b.Property<int?>("InitialStatusCodeRaw")
                        .HasColumnType("int");

                    b.Property<DateTime?>("InitialStatusDateUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("InitialStatusText")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<bool>("NotificationsEnabled")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<int>("TrademarkId")
                        .HasColumnType("int");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("TrademarkId");

                    b.HasIndex("UserId", "TrademarkId")
                        .IsUnique()
                        .HasFilter("[IsDeleted] = 0");

                    b.ToTable("Watchlists");
                });

            modelBuilder.Entity("IPNoticeHub.Infrastructure.Identity.ApplicationUser", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.ToTable("AspNetUsers", (string)null);

                    b.HasData(
                        new
                        {
                            Id = "2b195b12-9690-46b9-ac8e-50118a7102ea",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "73dd29f5-cb9c-4f43-84ae-73597cded863",
                            Email = "testuser1@example.com",
                            EmailConfirmed = true,
                            LockoutEnabled = false,
                            NormalizedEmail = "TESTUSER1@EXAMPLE.COM",
                            NormalizedUserName = "TESTUSER1@EXAMPLE.COM",
                            PasswordHash = "AQAAAAIAAYagAAAAEFakeHash1234567890==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "6fc62e55-dbc8-4022-84b4-cd49bdb663a3",
                            TwoFactorEnabled = false,
                            UserName = "testuser1@example.com"
                        },
                        new
                        {
                            Id = "4d8f7a3e-cb13-42f4-bf61-0a8c301a3f8b",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "d1d41029-3bbf-4476-890a-d64104220466",
                            Email = "testuser2@example.com",
                            EmailConfirmed = true,
                            LockoutEnabled = false,
                            NormalizedEmail = "TESTUSER2@EXAMPLE.COM",
                            NormalizedUserName = "TESTUSER2@EXAMPLE.COM",
                            PasswordHash = "AQAAAAIAAYagFakeHash0987654321==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "abc60a70-c408-4762-be78-c7c0d1ea3b9b",
                            TwoFactorEnabled = false,
                            UserName = "testuser2@example.com"
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("AspNetRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("RoleId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("IPNoticeHub.Domain.Entities.Identity.UserCopyright", b =>
                {
                    b.HasOne("IPNoticeHub.Infrastructure.Identity.ApplicationUser", null)
                        .WithMany("UserCopyrights")
                        .HasForeignKey("ApplicationUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("IPNoticeHub.Domain.Entities.Copyrights.CopyrightEntity", "CopyrightEntity")
                        .WithMany("UserCopyrights")
                        .HasForeignKey("CopyrightEntityId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("CopyrightEntity");
                });

            modelBuilder.Entity("IPNoticeHub.Domain.Entities.Identity.UserTrademark", b =>
                {
                    b.HasOne("IPNoticeHub.Infrastructure.Identity.ApplicationUser", null)
                        .WithMany("UserTrademarks")
                        .HasForeignKey("ApplicationUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("IPNoticeHub.Domain.Entities.Trademarks.TrademarkEntity", "TrademarkEntity")
                        .WithMany("UserTrademarks")
                        .HasForeignKey("TrademarkEntityId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("TrademarkEntity");
                });

            modelBuilder.Entity("IPNoticeHub.Domain.Entities.LegalDocuments.LegalDocument", b =>
                {
                    b.HasOne("IPNoticeHub.Infrastructure.Identity.ApplicationUser", null)
                        .WithMany("LegalDocuments")
                        .HasForeignKey("ApplicationUserId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();
                });

            modelBuilder.Entity("IPNoticeHub.Domain.Entities.Trademarks.TrademarkClassAssignment", b =>
                {
                    b.HasOne("IPNoticeHub.Domain.Entities.Trademarks.TrademarkEntity", "TrademarkRegistration")
                        .WithMany("Classes")
                        .HasForeignKey("TrademarkRegistrationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("TrademarkRegistration");
                });

            modelBuilder.Entity("IPNoticeHub.Domain.Entities.Trademarks.TrademarkEvent", b =>
                {
                    b.HasOne("IPNoticeHub.Domain.Entities.Trademarks.TrademarkEntity", "TrademarkRegistration")
                        .WithMany("Events")
                        .HasForeignKey("TrademarkId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("TrademarkRegistration");
                });

            modelBuilder.Entity("IPNoticeHub.Domain.Entities.Watchlist.Watchlist", b =>
                {
                    b.HasOne("IPNoticeHub.Domain.Entities.Trademarks.TrademarkEntity", "Trademark")
                        .WithMany()
                        .HasForeignKey("TrademarkId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Trademark");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("IPNoticeHub.Infrastructure.Identity.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("IPNoticeHub.Infrastructure.Identity.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("IPNoticeHub.Infrastructure.Identity.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("IPNoticeHub.Infrastructure.Identity.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("IPNoticeHub.Domain.Entities.Copyrights.CopyrightEntity", b =>
                {
                    b.Navigation("UserCopyrights");
                });

            modelBuilder.Entity("IPNoticeHub.Domain.Entities.Trademarks.TrademarkEntity", b =>
                {
                    b.Navigation("Classes");

                    b.Navigation("Events");

                    b.Navigation("UserTrademarks");
                });

            modelBuilder.Entity("IPNoticeHub.Infrastructure.Identity.ApplicationUser", b =>
                {
                    b.Navigation("LegalDocuments");

                    b.Navigation("UserCopyrights");

                    b.Navigation("UserTrademarks");
                });
#pragma warning restore 612, 618
        }
    }
}
